# Generated by Django 5.0.1 on 2024-02-16 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('id_device', models.ForeignKey(db_column='id_device', on_delete=django.db.models.deletion.CASCADE, to='datamanage.device')),
            ],
        ),
    ]
