# Generated by Django 5.0.1 on 2024-02-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0002_ping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ping',
            name='id_device',
        ),
    ]
